### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by StickBarrel** [RustyMods/PortalStations#2]
Hello, how do I get the portable portal? I don't think I can do it or is it some shortcut key?

**Comment by RustyMods** [comment]
its an item you make

**Comment by StickBarrel** [comment]
Where can I do it? because I saw that in the configuration it is done in the forge but there is no such item to do.

**Comment by RustyMods** [comment]
build it on the forge. config says recipe

**Comment by StickBarrel** [comment]
Yes, but the item to do so does not appear.

**Comment by StickBarrel** [comment]
Look, my forge is already at level 6. I even left it at 2 to see if it appeared as shown in the configuration.

**Comment by StickBarrel** [comment]
I even tried to change where to make the item but without success it appeared.

**Comment by StickBarrel** [comment]
I'm sorry friend, I was looking deeper and hadn't seen that I needed yimir meat. After picking it up, the portable appeared! Thanks.
